name: jeecgboot_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+2
  flutter_secure_storage: ^3.3.1+1
  fancy_bottom_navigation: ^0.3.2
  dio: ^3.0.9
  cached_network_image: ^2.0.0
  path_provider: ^1.6.1

  # video/audio player
  # https://github.com/flutter/plugins/tree/master/packages/video_player/video_player
  video_player: ^0.10.8+1
  # https://github.com/luanpotter/audioplayers
  audioplayers: ^0.14.0

  # video/audio/picture/file picker
  # https://github.com/miguelpruivo/flutter_file_picker
  file_picker: ^1.4.3+2
  # https://github.com/flutter/plugins/blob/master/packages/image_picker/
  # image_picker: ^0.6.3+4

  # date/time/datetime picker
  # https://github.com/jifalops/datetime_picker_formfield
  datetime_picker_formfield: ^1.0.0
  # https://github.com/Realank/flutter_datetime_picker
  # flutter_datetime_picker: ^1.3.4

  # https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.4

  # https://pub.dev/packages/progress_dialog
  progress_dialog: ^1.2.1
  # https://pub.dev/packages/flutter_custom_dialog
  # https://github.com/YYFlutter/flutter-custom-dialog
  # flutter_custom_dialog: ^1.0.16
  # https://pub.dev/packages/fancy_dialog
  fancy_dialog: ^1.0.3
  # https://pub.dev/packages/giffy_dialog
  giffy_dialog: ^1.7.0
  # https://github.com/danvick/flutter_form_builder
  flutter_form_builder: ^3.8.0+1
  # https://pub.dev/packages/downloader
  # https://github.com/Git-Ashwin/Downloader/blob/master/example/lib/main.dart
  downloader: ^0.0.1
  # https://pub.dev/packages/flutter_downloader#-installing-tab-
  # https://github.com/fluttercommunity/flutter_downloader/blob/master/example/lib/main.dart
  flutter_downloader: ^1.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/alucard.jpg
    - assets/001-boy.png
    - assets/fine-cut.mp3
    - assets/loveyou-cut.mp4
    - assets/men_wearing_jacket.gif
    - assets/space_demo.flr
  # fonts:
  #     - family: Nunito
  #       fonts:
  #         - asset: assets/Nunito.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
